### ISSUE TITLE
Improve CLI help/usage formatting

### ISSUE THREAD

**Issue by alykhank** [sleekbyte/tailor#126]
**Current**

```
$ tailor -h
usage: tailor
 -h,--help                        display help
 -l,--max-line-length <arg>       maximum Line length (in characters)
    --max-class-length <arg>      maximum Class length (in lines)
    --max-closure-length <arg>    maximum Closure length (in lines)
    --max-file-length <arg>       maximum File length (in lines)
    --max-function-length <arg>   maximum Function length (in lines)
    --max-name-length <arg>       maximum Identifier name length (in
                                  characters)
    --max-severity <arg>          maximum severity [error|warning]
    --max-struct-length <arg>     maximum Struct length (in characters)
```

**TODO**
- [x] Edit usage message to explain options and arguments

```
usage: tailor [options] [[file|directory] ...]
```
- [x] Provide summary message like `Perform static analysis on Swift source files.`
- [x] Explain Xcode integration (`$SRCROOT` detection) and setup instructions
- [x] Increase the maximum character width of `printHelp()` to prevent unnecessary wrapping.
- [x] Add `[-v|--version]` argument
- [x] Use more informative `argName` values for each option
